name: Build windows plugin package

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Execute release.ps1
      run: ./release.ps1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: TwoFactorAuthenticator
        path: Flow.Launcher.Plugin.YoudaoTranslate/bin/YoudaoTranslate.zip

    - name: Release artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Flow.Launcher.Plugin.YoudaoTranslate/bin/YoudaoTranslate.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}